---

- name: GET-1
  tags: ex-get-1
  block:
    - ucl:
        path: /etc/pkg/FreeBSD.conf
        upath: .
      register: result
    - ansible.builtin.debug:
        msg: "{{ msg.splitlines() }}"
      vars:
        msg: |-
          {{ result | to_nice_yaml }}
      when: debug | d(false) | bool

- name: GET-2
  tags: ex-get-2
  block:
    - ucl:
        path: /etc/pkg/FreeBSD.conf
        upath: freebsd.url
      register: result
    - ansible.builtin.set_fact:
        freebsd_url: "{{ result.stdout }}"
    - ansible.builtin.debug:
        msg: "{{ msg.splitlines() }}"
      vars:
        msg: |-
          {{ result | to_nice_yaml }}
      when: debug | d(false) | bool

- name: GET-3
  tags: ex-get-3
  block:
    - ucl:
        path: /etc/pkg/FreeBSD.conf
        lang: yaml
      register: result
    - ansible.builtin.debug:
        msg: "{{ msg.splitlines() }}"
      vars:
        msg: |-
          {{ result | to_nice_yaml }}
      when: debug | d(false) | bool
