---
- name: SET-3
  tags: ex-set-3
  block:
    - ucl:
        path: /etc/pkg/FreeBSD.conf
        upath: freebsd.url
      register: result
    - ansible.builtin.set_fact:
        freebsd_url: "{{ result.stdout }}"

- name: SET-1
  tags: ex-set-1
  block:
    - ucl:
        path: /etc/pkg/FreeBSD.conf
        upath: freebsd.url
        value: "pkg+http://pkg.FreeBSD.org/${ABI}/latest"
      register: result
    - ansible.builtin.debug:
        msg: "{{ msg.splitlines() }}"
      vars:
        msg: |-
          {{ result | to_nice_yaml }}
      when: debug | d(false) | bool

- name: SET-2
  tags: ex-set-2
  block:
    - ucl:
        path: /etc/pkg/FreeBSD.conf
        upath: freebsd.url
        value: "pkg+http://pkg.FreeBSD.org/${ABI}/quarterly"
      register: result
    - ansible.builtin.debug:
        msg: "{{ msg.splitlines() }}"
      vars:
        msg: |-
          {{ result | to_nice_yaml }}
      when: debug | d(false) | bool

- name: SET-3
  tags: ex-set-3
  block:
    - ucl:
        path: /etc/pkg/FreeBSD.conf
        upath: freebsd.url
        value: "{{ freebsd_url }}"
      register: result
    - ansible.builtin.debug:
        msg: "{{ msg.splitlines() }}"
      vars:
        msg: |-
          {{ result | to_nice_yaml }}
      when: debug | d(false) | bool
