---

# NOTE: Copy *uclcmd* to *uclcmd-v2* to test the option *executable*
# or env *ANSIBLE_UCLCMD*

- name: Examples. ANSIBLE_UCLCMD
  tags: ex-uclcmd-1
  block:
    - name: Get upath.
      environment:
        ANSIBLE_UCLCMD: /usr/local/bin/uclcmd-v2
      register: result
      ucl:
        path: /etc/pkg/FreeBSD.conf
        upath: freebsd.url
    - ansible.builtin.debug:
        var: result
      when: debug | d(false) | bool

- name: Examples. ANSIBLE_UCLCMD
  tags: ex-uclcmd-2
  block:
    - name: Get upath.
      register: result
      ucl:
        path: /etc/pkg/FreeBSD.conf
        upath: freebsd.url
        executable: /usr/local/bin/uclcmd-v2
    - ansible.builtin.debug:
        var: result
      when: debug | d(false) | bool
