---
- name: "Patch tests"
  register: result
  delegate_to: localhost
  debug:
    msg: "{{ item }}"
  loop: "{{ q('ansible.builtin.fileglob', playbook_dir ~ '/files/*.patch') }}"

- name: "Debug result."
  when: debug | d(false) | bool
  ansible.builtin.debug:
    var: result

- ansible.builtin.meta: end_play
