---

# Create dictionary that will control the tests

- ansible.builtin.set_fact:
    _tests: {}

- name: Create dictionary _tests
  vars:
    _test_key: "{{ item.1 }}"
    _test_val: "{{ dict(['cmd', 'dif', 'tmp', 'res'] | zip([_cmd, _dif, _tmp, _res])) }}"
    _test_path: "{{ tests_dir}}/{{ item.1 }}"
    _in: "{{ tests_dir }}/{{ item.0.key }}"
    _tmp: "{{ tmp_dir }}/{{ item.1 | splitext | first }}.tmp"
    _cmd: "cat {{ _in }} | {{ uclcmd }} $(cat {{ _test_path }}) > {{ _tmp }}"
    _res: "{{ tests_dir }}/{{ item.1 | splitext | first }}.res"
    _dif: "{{ 'diff -B ' ~ _res ~ ' ' ~ _tmp }}"
  ansible.builtin.set_fact:
    _tests: "{{ _tests | combine({_test_key: _test_val}) }}"
  loop: "{{ tests_files | dict2items | subelements('value') }}"

- ansible.builtin.debug:
    var: _tests
  when: debug2 | d(false) | bool

- name: Run the tests and optionally display the results.
  block:
    - name: Run command uclcmd
      changed_when: false
      ansible.builtin.shell: # noqa: command-instead-of-shell
        cmd: "{{ item.value.cmd }}"
        chdir: "{{ run_dir }}"
      register: tests_res
      check_mode: false
      loop: "{{ _tests | dict2items }}"
      loop_control:
        label: "{{ item.key }}"
  rescue:
    - ansible.builtin.debug:
        msg: "[ERR] Some of the tests failed. See debug for details."
    - ansible.builtin.debug:
        msg: "{{ ansible_failed_result.results | selectattr('rc', 'ne', 0) | list }}"
      when: debug2 | d(false) | bool

- name: Debug3 tests_res
  when: debug3 | d(false) | bool
  ansible.builtin.debug:
    var: tests_res

- name: Diff results
  changed_when: false
  ignore_errors: true
  ansible.builtin.shell: # noqa: command-instead-of-shell
    cmd: "{{ item.item.value.dif }}"
  register: tests_diff
  check_mode: false
  loop: "{{ tests_res.results }}"
  loop_control:
    label: "{{ item.item.key }}"
